Revert "system/gatekeeper: use proper nativehelper headers"
This reverts commit 05b35791c3079543c680efba0789f03cfddafacb.

...
In file included from system/gatekeeper/gatekeeper.cpp:16:
In file included from system/gatekeeper/include/gatekeeper/gatekeeper.h:22:
libnativehelper/include/nativehelper/UniquePtr.h:20:10: fatal error: 'cstdlib' file not found
#include <cstdlib> // For NULL.

Exempt-From-Owner-Approval: build breakage

Change-Id: Ib6e181046504b2559093ce6d92d9d701a527ba01